### ISSUE TITLE
Avoid cluttering source directory with compiled `.so` files

### ISSUE THREAD

**Issue by b0o** [ofek/hatch-mypyc#39]
Running the build puts compiled files in the source directory before building the wheel and doesn't clean them up. Is there a way to run the build in a temporary directory to avoid this? I only want compiled files in the wheel.

```toml
[tool.hatch.build.targets.wheel.hooks.mypyc]
dependencies = ["hatch-mypyc"]
```
